name: micro_emploi_app
description: A Flutter app for partial work platform
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0  # للتاريخ DateFormat
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  lottie: ^3.1.2
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  geocoding: ^2.1.1
  # مكتبات إدارة الثيم
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # المكتبات الجديدة المطلوبة للخرائط والموقع
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.1
  location: ^5.0.3
  geolocator: ^10.1.0
  flutter_foreground_task: ^8.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/mr.svg
    - assets/animations/loader.json